[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = "0.37.0"
serde_json = "1.0.143"
